[window]
opacity = 0.6
blur = true
[colors.primary]
background = "#000000"
foreground = "#ffffff"
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13.0
